{% set version = "0.7.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dnapath
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dnapath_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dnapath/dnapath_{{ version }}.tar.gz
  sha256: ec0ff2184e1a7cda813ed66dec7914950e6fe31f3c970aca2de1cc7d610a42b5

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.1
    - r-rcpparmadillo
    - r-rdpack
    - r-seqnet
    - r-corpcor
    - r-curl
    - r-dplyr
    - r-ggplot2
    - r-gtools
    - r-igraph
    - r-tibble
    - r-wcorr
  run:
    - r-base
    - r-rcpp >=1.0.1
    - r-rcpparmadillo
    - r-rdpack
    - r-seqnet
    - r-corpcor
    - r-curl
    - r-dplyr
    - r-ggplot2
    - r-gtools
    - r-igraph
    - r-tibble
    - r-wcorr

test:
  commands:
    - $R -e "library('dnapath')"           # [not win]
    - "\"%R%\" -e \"library('dnapath')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=dnapath
  license: GPL-2.0-or-later
  summary: Integrates pathway information into the differential network analysis of two gene expression datasets as described in Grimes, Potter, and Datta (2019) <doi:10.1038/s41598-019-41918-3>. Provides summary functions to break down the results at the pathway, gene, or individual connection level. The differential networks
    for each pathway of interest can be plotted, and the visualization will highlight any differentially expressed genes and all of the gene-gene associations that are significantly differentially connected.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
